config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('tienda.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

tienda/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name='tienda'

urlpatterns = [
    # paths del menú
    path('', views.index, name='index'),
    path('categorias/', views.listCategorias, name='categorias'),
    path('contacto/', views.contacto, name='contacto'),
    path('garantia/', views.garantia, name='garantia'),
    path('devoluciones/', views.devoluciones, name='devoluciones'),
    path('nosotros/', views.nosotros, name='nosotros'),

    path('producto/', views.detalleProducto, name='producto'),
    path('addproducto/', views.addProducto, name='addproducto'),
    path('detalleproducto/<id>/', views.detalleProducto, name='detalleproducto'),
    path('detalle/<id>/', views.detalleProducto, name='detalle'),
    path('productocategoria/<id>/', views.productoxCategoria, name='productocategoria'),
    path('editproducto/<id>/', views.editarProducto, name='editproducto'),
    path('deleteProducto/<id>/', views.deleteProducto, name='deleteProducto'),
    path('listarproductos/', views.listarProductos, name='listarproductos'),
    path('addcategoria/', views.addCategoria, name='addcategoria'),
    path('editcategoria/<id>/', views.modificarCategoria, name='editcategoria'),
    path('deleteCategoria/<id>/', views.deleteCategoria, name='deleteCategoria'),
        
    # paths del registrar
    path('registrar/', views.registrar, name='registrar'),
    path('login/', LoginView.as_view(template_name='auth/login.html'), name='login'),
    
    #Paths del carrito
    path('viewcart/', views.viewcart, name="viewcart"),

    path('addcart/<producto_id>/', views.agregar_producto, name="addcart"),

    path('delcart/<producto_id>/', views.eliminar_producto, name="delcart"),

    path('restarcart/<producto_id>/', views.restar_producto, name="restarcart"),

    path('cleancart/', views.cleancart, name="cleancart"),

    path('procesar_compra/', views.procesar_compra, name="procesar_compra"),
    
]

templates/carrito/cart.html
{% extends 'layouts/tienda.html' %} {% block content %}
<div class="min-vh-100 d-flex flex-colum py-4">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-9 col-md-8 col-sm-6 mx-auto ">

                <div class="card">
                    <div class="card-header text-center">
                        <strong>CARRITO</strong>
                    </div>
                    <div class="card body p-2">
                        {% load humanize %}
                        <h6>Total: <strong> 
                            $ {{ importe_total_carro | intcomma }}
                        </strong></h6>

                    </div>

                    <div class="card-element table-responsive">
                        <table class="table table-condensed">
                            <thead class="text-center">
                                <tr>
                                    <th>Item</th>
                                    <th colspan="3">Cantidad</th>
                                    <th>Subtotal</th>
                                    <th>Eliminar</th>
                                </tr>
                            </thead>
                            <tbody class="py-4">
                                {% if request.session.carro.items %} {% for key, value in request.session.carro.items %}
                                <tr>
                                    <td>{{ value.nombre }}</td>

                                    {% load bootstrap_icons %}
                                    <td class="text-center" colspan="3">
                                        {{ value.cantidad }}
                                        <a href="{% url 'tienda:addcart' value.producto_id %}" class="btn btn-secondary btn-sm" type="button"><i class="bi bi-plus"></i></a>

                                        <a class="btn btn-secondary btn-sm" href="{% url 'tienda:restarcart' value.producto_id %}" type="button"><i class="bi bi-dash"></i> </a>
                                    </td>

                                    <td class="text-center">${{ value.precio }} </td>
                                    <td class="text-center">
                                        <a class="btn btn-secondary btn-sm" href="{% url 'tienda:delcart' value.producto_id %}" type="button"><i class="bi bi-trash"></i></a>
                                    </td>
                                </tr>
                                {% endfor %} {% else %}
                                <tr>
                                    <td colspan="5">
                                        <div class="alert alert-danger text-center ">

                                            No se agregaron productos al carrito

                                        </div>
                                </tr>
                                </tr>
                                {% endif %}

                            </tbody>
                        </table>

                    </div>

                    <div class="card-footer mx-auto ">
                        {% if request.session.carro.items %}
                        <a class="btn btn-danger mx-auto mt-0 " href="{% url 'tienda:procesar_compra' %}">Procesar Compra</a> {% else %}
                        <a class="btn btn-danger mx-auto mt-0 disabled" href="#">Procesar Compra</a> {% endif %}
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-4 col-sm-3 my-4 mx-auto ">
                <div class="card card-footer align-item-center ">
                    <a href="/ " class="btn btn-dark my-2 mx-auto ">Volver a Tienda</a>
                    <a href="{% url 'tienda:cleancart' %}" class="btn btn-dark my-2 mx-auto ">Limpiar Carrito</a>
                </div>

            </div>

        </div>
    </div>
</div>
{% endblock %}

templates/carrito/checkout.html
{% extends 'layouts/tienda.html' %} {% block content %}
<div class="min-vh-100 d-flex flex-colum py-3">
    <div class="container-fluid">
        <h3 class="animate__animated animate__bounceInDown animate__delay-0.3s text-center my-3">CHECKOUT</h3>

        <div class="row">
            <div class="col-6 mx-auto animate__animated animate__bounceInUp animate__delay-0.4s">
                <div class="card p-4">
                    <form method="get" action="">
                        <h5 class="text-center">
                            <strong>Información del comprador</strong></h5>
                        <div class="form-group">
                            <input id="nombre" class="form-control mb-2 mr-sm-2" type="text" name="nombre" placeholder="{{ user.username }}" readonly>
                        </div>
                        <div class="form-group">
                            <input id="email" class="form-control mb-2 mr-sm-2" type="email" name="email" placeholder="{{ user.email }}" readonly>
                        </div>

                        <h5 class="text-center"><strong>Información para la Entrega</strong></h5>
                        <div class="row">
                            <div class="col">
                                <input id="ciudad" class="form-control mb-2 mr-sm-1" type="text" name="ciudad" placeholder="Ciudad de entrega">
                            </div>

                            <div class="col">
                                <input id="direccion" class="form-control mb-2 mr-sm-1" type="text" name="direccion" placeholder="Dirección de entrega">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <input id="codigo" class="form-control mb-2 mr-sm-1" type="text" name="codigo" placeholder="Código Postal">
                            </div>
                            <div class="col">
                                <input id="telefono" class="form-control mb-2 mr-sm-1" type="text" name="telefono" placeholder="Teléfono de contacto">
                            </div>
                        </div>
                        <hr>
                        <div class="text-center">
                            <a class="btn btn-dark" type="submit"> Confirmar Info </a>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-6 mx-auto animate__animated animate__bounceInUp animate__delay-0.5s ">
                <div class="card p-4">

                    <a class="btn btn-dark mx-auto my-auto" href="{% url 'tienda:cart' %}"> Volver al carrito </a>
                    <hr>
                    <h5 class="mx-auto"><strong>Resumen de la Compra</strong></h5>
                    <p><strong>Items:{{ order.get_cart_items }}  </strong></p>
                    <p><strong>Total:{{ order.get_total_order }} </strong></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}