config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('tienda.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

tienda/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name='tienda'

urlpatterns = [
    # paths del menú
    path('', views.index, name='index'),
    path('categorias/', views.listCategorias, name='categorias'),
    path('contacto/', views.contacto, name='contacto'),
    path('garantia/', views.garantia, name='garantia'),
    path('devoluciones/', views.devoluciones, name='devoluciones'),
    path('nosotros/', views.nosotros, name='nosotros'),

    path('producto/', views.detalleProducto, name='producto'),
    path('addproducto/', views.addProducto, name='addproducto'),
    path('detalleproducto/<id>/', views.detalleProducto, name='detalleproducto'),
    path('detalle/<id>/', views.detalleProducto, name='detalle'),
    path('productocategoria/<id>/', views.productoxCategoria, name='productocategoria'),
    path('editproducto/<id>/', views.editarProducto, name='editproducto'),
    path('deleteProducto/<id>/', views.deleteProducto, name='deleteProducto'),
    path('listarproductos/', views.listarProductos, name='listarproductos'),
    path('addcategoria/', views.addCategoria, name='addcategoria'),
    path('editcategoria/<id>/', views.modificarCategoria, name='editcategoria'),
    path('deleteCategoria/<id>/', views.deleteCategoria, name='deleteCategoria'),
        
    # paths del registrar
    path('registrar/', views.registrar, name='registrar'),
    path('login/', LoginView.as_view(template_name='auth/login.html'), name='login'),
    
    #Paths del carrito
    path('viewcart/', views.viewcart, name="viewcart"),

    path('addcart/<producto_id>/', views.agregar_producto, name="addcart"),

    path('delcart/<producto_id>/', views.eliminar_producto, name="delcart"),

    path('restarcart/<producto_id>/', views.restar_producto, name="restarcart"),

    path('cleancart/', views.cleancart, name="cleancart"),

    path('procesar_compra/', views.procesar_compra, name="procesar_compra"),
    
]

templates/producto/agregar.html
{% extends 'layouts/tienda.html' %} {% block content %}
<div class="min-vh-100 d-flex flex-colum py-4">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-8 mx-auto animate__animated animate__backInRight animate__delay-0.5s mt-3">
                {% load crispy_forms_tags %}
                <div class="card p-2">
                    <h3 class="animate__animated animate__bounceInDown animate__delay-1s text-center my-2">PRODUCTO</h3>
                    <div class="card body p-2">
                        <form action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %} {{ form | crispy }}
                            <div class="d-flex justify-content-end">
                                <a href="/listarproductos" class="btn btn-secondary mt-2 mx-2" button ">Cancelar</a>
                        <button type="submit " class="btn btn-danger mt-2 mx-2 " button ">Agregar</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

templates/producto/detalle.html
{% extends "layouts/tienda.html" %} {% block content %}

<!-- Productos detalles-->
<section class="py-5">
    <div class="container px-4 px-lg-5 my-3">
        <div class="row gx-4 gx-lg-5 align-items-center">
            {% if producto.imagen %}
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ producto.imagen.url }}" /></div>
            {% else %}
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." /></div>
            {% endif %}
            <div class="col-md-6">
                <div class="small mb-1">Código: {{ producto.id }}</div>
                <h1 class="display-5 fw-bolder">{{ producto.nombre }}</h1>
                <div class="fs-5 mb-5">
                    <!-- <span class="text-decoration-line-through">Gs. {{ producto.precio }}</span> -->
                    <span>$ {{ producto.precio }} </span>
                    
                </div>
                <p class="lead">{{ producto.descripcion }}</p>
                <div class="d-flex">
                    <input class="form-control text-center me-3" id="inputQuantity" type="num" value="1" style="max-width: 3rem" /> {% if user.is_authenticated%}
                    <a href="{% url 'tienda:addcart' producto.id %}" class="btn btn-outline-dark flex-shrink-0" type="button">
                        <i class="bi-cart-fill me-1"></i> Agregar al Carrito
                    </a> {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
<table class="table table-condensed">
    <thead class="thead-dark text-center ">
        <tr>
            <th scope="col">Fecha</th>
            <th scope="col">Precio Antiguo</th>
            <th scope="col">Precio Nuevo</th>
            <th scope="col">Contador</th>
        
        </tr>
    </thead>
    <tbody>
        {% load bootstrap_icons %} {% if comparacion %} {% for c in comparacion %}
        <tr>
            <td class="text-center">{{ c.fecha }}</td>
            <td class="text-center">{{ c.precioAntiguo }}</td>
            <td class="text-center">{{ c.precioNuevo }}</td>
            <td class="text-center">{{ forloop.counter }}</td>
            
        </tr>
        {% endfor %} {% else %}
        <div class="text-center text-warning">
            <h3> No existen productos</h3>
        </div>
        {% endif %}
    </tbody>
</table>



<!-- Relacion de productos-->
<section class="py-3 bg-light">
    <div class="container px-3 px-lg-5 mt-3">
        <h2 class="fw-bolder mb-4 text-center">Productos relacionados</h2>
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for product in productosRelacionados %} {% if product.id == producto.id %} {% else %}
            <div class="col mb-5">
                <div class="card h-100">
                    {% if product.imagen %}
                    <!-- Producto imagen-->
                    <img class="card-img-top" src="{{ product.imagen.url }}" /> {% else %}
                    <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="producto" /> {% endif %}
                    <!-- Producto detalle-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Producto nombre-->
                            <h5 class="fw-bolder">{{ product.nombre }}</h5>
                            <!-- Producto precio-->
                            $ {{ product.precio }}
                        </div>
                    </div>
                    <!-- Producto agregar-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center">
                            <a class="btn btn-outline-dark mt-auto" href="#"> <i class="bi-cart-fill me-1"></i>Al Carrito</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %} {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

templates/producto/listar.html
{% extends 'layouts/tienda.html' %} {% block content %}
<div class="min-vh-100 d-flex flex-colum py-4">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-10 col-md-6 col-sm-4 animate__animated animate__backInRight animate__delay-0.4s">
                <div class="card">
                    <div class="card-header text-center font-weight-bold">
                        {{ title }}
                    </div>
                    <div class="card-body table-responsive align-items-center">
                        <!-- inline-block justify-content-end mb-2 mx-2 -->
                        <div class="d-flex mb-2">
                            <a href="/addproducto" class="d-flex inline-block mx-auto btn btn-dark btn-sm" type="submit">
                                Nuevo Producto
                            </a>

                            <form class="d-flex mx-auto d-sm-inlne-block form-inline" method="POST" action="">
                                {% csrf_token %}
                                <div class="input-group">
                                    <input type="text" class="form-control bg-light border-1 small text-center" name="buscador" placeholder="buscar..." value="{{ request.POST.buscador }}">
                                    <div class="input-group-append">
                                        <button class="btn btn-danger mx-1" type="submit"> 
                                                <i class="bi bi-search bi-sm"></i>
                                            </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <table class="table table-condensed">
                            <thead class="thead-dark text-center ">
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">descripcion</th>
                                    <th scope="col">precio</th>
                                    <th scope="col">stock</th>
                                    <th scope="col">categoria</th>
                                    <th colspan="2">Opciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% load bootstrap_icons %} {% if entity %} {% for producto in entity %}
                                <tr>
                                    <td>{{ producto.id }}</td>
                                    <td>{{ producto.nombre }}</td>
                                    <td>{{ producto.precio }}</td>
                                    <td>{{ producto.stock }}</td>
                                    <td>{{ producto.categoria }}</td>
                                    <td colspan="2">
                                        <a class="btn btn-secondary btn-sm" href="{% url 'tienda:editproducto' producto.id %}" type="button"><i class="bi bi-pencil-square"></i></a>
                                        <a class="btn btn-danger btn-sm" href="{% url 'tienda:deleteProducto' producto.id %}" type="button"><i class="bi bi-trash-fill"></i></a>
                                    </td>
                                </tr>
                                {% endfor %} {% else %}
                                <div class="text-center text-warning">
                                    <h3> No existen productos</h3>
                                </div>
                                {% endif %}
                            </tbody>
                        </table>
                        <div>
                            {% include 'paginator.html' %}
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/producto/modificar.html
{% extends 'layouts/tienda.html' %} {% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-8 mx-auto animate__animated animate__backInRight animate__delay-0.5s mt-3">
            {{ mensaje }} {% load crispy_forms_tags %}
            <div class="card p-2">
                <h3 class="animate__animated animate__bounceInDown animate__delay-1s text-center my-2">MODIFICAR PRODUCTO</h3>
                <div class="card body p-2">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %} {{ form | crispy }}
                        <div class="d-flex justify-content-end">
                            <a href="/listarproductos" class="btn btn-secondary mt-2 mx-2" button ">Cancelar</a>
                            <button type="submit " class="btn btn-danger mt-2 mx-2 " button ">Modificar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

</div>
{% endblock %}