config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('tienda.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

tienda/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name='tienda'

urlpatterns = [
    # paths del menú
    path('', views.index, name='index'),
    path('categorias/', views.listCategorias, name='categorias'),
    path('contacto/', views.contacto, name='contacto'),
    path('garantia/', views.garantia, name='garantia'),
    path('devoluciones/', views.devoluciones, name='devoluciones'),
    path('nosotros/', views.nosotros, name='nosotros'),

    path('producto/', views.detalleProducto, name='producto'),
    path('addproducto/', views.addProducto, name='addproducto'),
    path('detalleproducto/<id>/', views.detalleProducto, name='detalleproducto'),
    path('detalle/<id>/', views.detalleProducto, name='detalle'),
    path('productocategoria/<id>/', views.productoxCategoria, name='productocategoria'),
    path('editproducto/<id>/', views.editarProducto, name='editproducto'),
    path('deleteProducto/<id>/', views.deleteProducto, name='deleteProducto'),
    path('listarproductos/', views.listarProductos, name='listarproductos'),
    path('addcategoria/', views.addCategoria, name='addcategoria'),
    path('editcategoria/<id>/', views.modificarCategoria, name='editcategoria'),
    path('deleteCategoria/<id>/', views.deleteCategoria, name='deleteCategoria'),
        
    # paths del registrar
    path('registrar/', views.registrar, name='registrar'),
    path('login/', LoginView.as_view(template_name='auth/login.html'), name='login'),
    
    #Paths del carrito
    path('viewcart/', views.viewcart, name="viewcart"),

    path('addcart/<producto_id>/', views.agregar_producto, name="addcart"),

    path('delcart/<producto_id>/', views.eliminar_producto, name="delcart"),

    path('restarcart/<producto_id>/', views.restar_producto, name="restarcart"),

    path('cleancart/', views.cleancart, name="cleancart"),

    path('procesar_compra/', views.procesar_compra, name="procesar_compra"),
    
]

tienda/models.py
from django.db import models
from django.contrib.auth import get_user_model
from itertools import count 
User = get_user_model()

class Categorias(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre
    
    class Meta:
        db_table = "categorias"
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['id']


#modelo Productos
class Productos(models.Model):
    nombre = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to='imgproductos/%Y/%m/%d', blank=True)
    descripcion = models.CharField(max_length=500)
    precio = models.IntegerField()
    stock = models.IntegerField(null=True, default=0)
    categoria = models.ForeignKey(Categorias, on_delete=models.PROTECT)
    oferta = models.BooleanField(default=False)

    def __str__(self):
        return self.nombre

    class Meta:
        db_table = 'productos'
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        ordering = ['id']


class Contacto(models.Model):
    nombre = models.CharField(max_length=100)
    correo = models.EmailField()
    mensaje = models.TextField()

    def __str__(self):
        return self.nombre
    class Meta:
        db_table = 'contacto'
        verbose_name = 'Contacto'
        verbose_name_plural = 'Contactos'
        ordering = ['nombre']


class ComparacionPrecios(models.Model):
    idProducto = models.ForeignKey(Productos, on_delete=models.PROTECT)
    fecha = models.DateField()
    precioAntiguo = models.IntegerField()
    precioNuevo = models.IntegerField()
    class Meta:
        db_table = 'ComparacionPrecios'
        verbose_name = 'ComparacionPrecios'
        verbose_name_plural = 'ComparacionPrecios'
        ordering = ['fecha']

tienda/forms.py
from django import forms
from .models import Contacto, Productos, Categorias
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ConctactoForm(forms.ModelForm):

    class Meta:
        model = Contacto
        widgets={
            'mensaje': forms.Textarea(attrs={
                'rows':5,
                'cols':30
                }),
        }
        fields = '__all__'


class ProductoForm(forms.ModelForm):

    class Meta:
        model = Productos
        fields = ["nombre", "descripcion", "precio", "stock", "categoria", "oferta", "imagen"]
        

class CategoriaForm(forms.ModelForm):

    class Meta:
        model = Categorias
        fields = ["nombre"]


class CustomUserCreationForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ["username", "first_name","last_name","email","password1","password2"]

tienda/views.py
from django.forms import DateField
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from .models import *
from .carro import Carro
from django.core.paginator import Paginator
from django.http import Http404
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.views.generic import ListView, CreateView
from django.db.models import Q
from .forms import ConctactoForm, ProductoForm, CategoriaForm, CustomUserCreationForm
from django.db.models import Avg
import statistics

import json

def index(request):
    busqueda = request.POST.get("buscador")
    product_list = Productos.objects.order_by('nombre')
    page = request.GET.get('page', 1)

    if busqueda:
        product_list = Productos.objects.filter(
            Q(nombre__icontains = busqueda) |
            Q(descripcion__icontains = busqueda)
        ).distinct()
    
    try:
        paginator = Paginator(product_list, 12)
        product_list = paginator.page(page)
    except:
        raise Http404

    data = {'entity': product_list,
            'paginator': paginator
    }
    return render(request, 'index.html', data)


# Listar productos por categoria
def productoxCategoria(request, id):
    busqueda = request.POST.get("buscador")
    lista_productos = Productos.objects.filter(categoria = id)
    
    if busqueda:
        lista_productos = Productos.objects.filter(
            Q(nombre__icontains=busqueda) |
            Q(descripcion__icontains=busqueda)
        ).distinct()

    data = {'entity': lista_productos}
    return render(request, 'index.html', data)


# views productos
def detalleProducto(request, id):
    product = get_object_or_404(Productos, id=id)
    otrosProductos = Productos.objects.filter(categoria=product.categoria)
    comparacion = ComparacionPrecios.objects.filter(idProducto=id)
    print(comparacion)
    prom = ComparacionPrecios.objects.filter(idProducto=id).aggregate(new=Avg(('precioNuevo')))
    print(prom)
    list =  [15,16,18]
    mean = statistics.mean(list)
    print(mean)
    data = {
        'producto': product,
        'productosRelacionados': otrosProductos,
        'comparacion': comparacion,
        'prom': prom,

    }
   
    return render(request, 'producto/detalle.html', data)

@login_required(login_url='/login')
def addProducto(request):
    data = {
        'form' : ProductoForm()
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES)

        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Registro agregado correctamente")
            return redirect(to="/listarproductos")
        else:
            data["form"] = formulario   
    return render(request, 'producto/agregar.html', data)


@login_required(login_url='/login')
def listarProductos(request):
    busqueda = request.POST.get("buscador")
    lista_productos = Productos.objects.order_by('nombre')
    page = request.GET.get('page', 1)
    if busqueda:
        lista_productos = Productos.objects.filter(
            Q(nombre__icontains = busqueda) |
            Q(descripcion__icontains = busqueda)
        ).distinct()

    try:
        paginator = Paginator(lista_productos, 6)
        lista_productos = paginator.page(page)
    except:
        raise Http404

    data = {'entity': lista_productos,
            'title': 'LISTADO DE PRODUCTOS',
            'paginator': paginator
            }
        
    return render(request, 'producto/listar.html', data)


@login_required(login_url='/login')
def editarProducto(request, id):
    producto = get_object_or_404(Productos, id=id)
    data = {
        'form': ProductoForm(instance=producto)
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, instance=producto, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Registro modificado correctamente")
            return redirect(to="/listarproductos")
        data["form"] = formulario
    return render(request, 'producto/modificar.html', data)


@login_required(login_url='/login')
def deleteProducto(request, id):
    producto = get_object_or_404(Productos, id=id)
    producto.delete()
    messages.success(request, "Registro eliminado correctamente")
    return redirect(to="/listarproductos")

def nosotros(request):
    return render(request, 'nosotros.html')

def garantia(request):
    return render(request, 'garantia.html')

def devoluciones(request):
    return render(request, 'devoluciones.html')


# Views categorias
@login_required(login_url='/login')
def listCategorias(request):
    lista_categorias = Categorias.objects.all().order_by('nombre')
    page = request.GET.get('page', 1)

    try:
        paginator = Paginator(lista_categorias, 6)
        lista_categorias = paginator.page(page)
    except:
        raise Http404

    data = {'entity': lista_categorias,
            'title': 'LISTADO DE CATEGORIAS',
            'paginator': paginator
            }

    return render(request,'categorias.html', data)


@login_required(login_url='/login')
def addCategoria(request):
    data = {
        'form': CategoriaForm()
    }
    if request.method == 'POST':
        formulario = CategoriaForm(data=request.POST)

        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Registro agregado correctamente")
            return redirect(to="/categorias")
        else:
            data["form"] = formulario
    return render(request, 'categoria/agregar.html', data)


@login_required(login_url='/login')
def modificarCategoria(request, id):
    categoria = get_object_or_404(Categorias, id=id)

    data = {
        'form': CategoriaForm(instance=categoria)
    }
    if request.method == 'POST':
        formulario = CategoriaForm(data=request.POST, instance=categoria)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Registro modificado correctamente")
            return redirect(to="/categorias")
        else:
            data["form"] = formulario

    return render(request, 'categoria/modificar.html', data)


@login_required(login_url='/login')
def deleteCategoria(request, id):
    categoria = get_object_or_404(Categorias, id=id)
    categoria.delete()
    messages.success(request, "Registro eliminado correctamente")
    return redirect(to="/categorias")

def contacto(request):
    data = {
        'form': ConctactoForm()
    }

    if request.method == 'POST':
        formulario = ConctactoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Gracias por su mensaje")
        else:
            data["form"] = formulario
    return render(request, 'contacto.html', data)


def registrar(request):
    data = {
        'form': CustomUserCreationForm()
    }

    if request.method == 'POST':
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data["username"], password=formulario.cleaned_data["password1"])
            login(request, user)
            messages.success(request, 'Usuario registrado correctamente')
            return redirect('/')
        else:
            data['form'] = formulario
    
    return render(request, 'auth/registrar.html', data)


# Acciones carrito
def viewcart(request):
    return render(request, 'carrito/cart.html', {'carro': request.session['carro']})

def agregar_producto(request, producto_id):
    carro=Carro(request)
    producto=Productos.objects.get(id=producto_id)
    carro.agregar(producto=producto)
    return redirect(to="/viewcart")

def eliminar_producto(request, producto_id):
    carro=Carro(request)
    producto=Productos.objects.get(id=producto_id)
    carro.eliminar(producto=producto)
    return redirect(to="/viewcart")


def restar_producto(request, producto_id):
    carro = Carro(request)
    producto = Productos.objects.get(id=producto_id)
    carro.restar(producto=producto)
    return redirect(to="/viewcart")

def cleancart(request):
    carro=Carro(request)
    carro.limpiar_carro()
    return redirect(to="/viewcart")


def procesar_compra(request):
    messages.success(request, 'Gracias por su Compra!!')
    carro = Carro(request)
    carro.limpiar_carro()
    return redirect('/')

templates/layouts/tienda.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="ecommerce productos" />
    <meta name="author" content="Kevin Herrera" />
    <title>Almacenes Loyola- Herrera</title>
    <!--icono de inicio-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/logo2.jpg' %} " />
    <!--estilos iconos de bootstrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!--estilos bootstrapp-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
   

    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
</head>

<body>
    <!-- Barra de navegacion-->
    <nav class="navbar navbar-expand-lg navbar-light bg-danger sticky-top">
        <div class="container px-2 px-lg-2">
           
            <a class="navbar-logo" href="/">
                <img class="img-fluid" src="{% static 'assets/logo2.jpg' %}" width="50%" heigth="50%" alt="logo">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/"></span>
                            Inicio
                        </a>
                    </li>

                    <!-- Menú desplegable -->
                    <div class="dropdown show">
                        <a class="nav-link dropdown-toggle text-dark" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Categorias
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            {% for categoria in categorias %}
                            <a class="dropdown-item" href="{% url 'tienda:productocategoria' categoria.id %}">{{categoria.nombre}}</a> {% endfor %}
                        </div>
                    </div>

                    {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/listarproductos">
                                Listado Productos
                            </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/categorias">
                                Listado Categorias
                            </a>
                    </li>

                    {% endif %}

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/nosotros">
                            Nosotros
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/contacto">
                            Contacto
                        </a>
                    </li>
                </ul>

                <ul class="navbar-nav d-flex ml-auto mb-2 mb-lg-0 ms-lg-4">
                    {% if user.is_authenticated %}
                    <!-- Si está registrado mostrara -->
                    {% load humanize %}
                    <div class="d-flex">
                        <a href="{% url 'tienda:viewcart' %}" class="btn btn-outline-dark">
                            <i class="bi-cart-fill me-1"></i>
                            <span class="badge bg-dark text-white ms-1 rounded-pill"> {{ importe_total_carro | intcomma }}</span>
                        </a>
                    </div>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">
                            <b>{{ user.username }}</b>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">
                                    Cerrar Sesión
                            </a>
                    </li>
                    {% else %}
                    <!-- Si no está registrado mostrara -->
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/login">
                            Ingresar
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/registrar">
                            Registrar
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <section class="container">
        <!-- CONTENIDO del LAYOUT -->
        {% block content%} {% endblock %}
    </section>

    <!-- Footer fixed-bottom-->
    <footer class="container-fluid my-0 pt-3 pb-0 bg-dark">
        <!-- <footer class="navbar fixed-bottom navbar-light bg-dark">-->
        <div class="row">
            <ul class="col-4 list-unstyled text-center mx-auto my-auto">
                <h6 class="text-white">Servicios</h6>
                <li class="list-unstyled text-white">
                    <a href="/garantia" class="stretched-link text-white">Servicio Técnico</a></li>
                <li>
                    <a href="/devoluciones" class="stretched-link text-white">Pandemia</a></li>

            </ul>
            <ul class="col-4 list-unstyled text-center mx-auto my-auto">
                <img class="img-fluid pb-1 " src="{% static 'assets/logo2.jpg' %}" alt="logo">
                <p class="font-weight-bold text-white text-center mb-1">ALMACENES LOYOLA</p>
                
            </ul>
            <ul class="col-4 list-unstyled my-auto mx-auto text-center">
                {% load bootstrap_icons %}
                <li>
                    <a href="#"> <i class="bi bi-facebook text-white mr-2"></i><span class="badge badge-danger">Facebook</span> </a>
                </li>
                <li>
                    <a href="#"> <i class="bi bi-whatsapp text-white mr-2"></i><span class="badge badge-danger">Whatsapp</span> </a>
                </li>
                <li>
                    <a href="#"> <i class="bi bi-instagram text-white mr-2"></i><span class="badge badge-danger">Instagram</span> </a>
                </li>
            </ul>
        </div>
        
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- MESSAGES-->
    {% if messages %} {% for message in messages %}
    <script>
        Swal.fire({
            "title": "Felicitaciones!!",
            "text": "{{ message }}",
            "icon": "success"
        })
    </script>
    {% endfor %} {% endif %}
    <!-- END MESSAGES -->
</body>

</html>