config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('tienda.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

tienda/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name='tienda'

urlpatterns = [
    # paths del menú
    path('', views.index, name='index'),
    path('categorias/', views.listCategorias, name='categorias'),
    path('contacto/', views.contacto, name='contacto'),
    path('garantia/', views.garantia, name='garantia'),
    path('devoluciones/', views.devoluciones, name='devoluciones'),
    path('nosotros/', views.nosotros, name='nosotros'),

    path('producto/', views.detalleProducto, name='producto'),
    path('addproducto/', views.addProducto, name='addproducto'),
    path('detalleproducto/<id>/', views.detalleProducto, name='detalleproducto'),
    path('detalle/<id>/', views.detalleProducto, name='detalle'),
    path('productocategoria/<id>/', views.productoxCategoria, name='productocategoria'),
    path('editproducto/<id>/', views.editarProducto, name='editproducto'),
    path('deleteProducto/<id>/', views.deleteProducto, name='deleteProducto'),
    path('listarproductos/', views.listarProductos, name='listarproductos'),
    path('addcategoria/', views.addCategoria, name='addcategoria'),
    path('editcategoria/<id>/', views.modificarCategoria, name='editcategoria'),
    path('deleteCategoria/<id>/', views.deleteCategoria, name='deleteCategoria'),
        
    # paths del registrar
    path('registrar/', views.registrar, name='registrar'),
    path('login/', LoginView.as_view(template_name='auth/login.html'), name='login'),
    
    #Paths del carrito
    path('viewcart/', views.viewcart, name="viewcart"),

    path('addcart/<producto_id>/', views.agregar_producto, name="addcart"),

    path('delcart/<producto_id>/', views.eliminar_producto, name="delcart"),

    path('restarcart/<producto_id>/', views.restar_producto, name="restarcart"),

    path('cleancart/', views.cleancart, name="cleancart"),

    path('procesar_compra/', views.procesar_compra, name="procesar_compra"),
    
]

templates/categorias.html
{% extends 'layouts/tienda.html' %} {% block content %}
<div class="min-vh-100 d-flex flex-colum py-4">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-6 col-sm-4 animate__animated animate__backInRight animate__delay-0.4s">
                <div class="card">
                    <div class="card-header text-center font-weight-bold">
                        {{ title }}
                    </div>
                    <div class="card-body  table-responsive">
                        <div class="d-flex justify-content-end mb-2 mx-2">
                            <a href="/addcategoria" class="btn btn-dark btn-sm pull-right" type="submit">
                            Nueva Categoria
                            </a>
                        </div>
                        <table class="table table-condensed">
                            <thead class="thead-dark">
                                <tr class="text-center">
                                    <th scope="col">#</th>
                                    <th scope="col">Nombre</th>
                                    <th colspan="2">Opciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% load bootstrap_icons %} {% if entity %} {% for categoria in entity %}
                                <tr>
                                    <td>{{ categoria.id }}</td>
                                    <td>{{ categoria.nombre }}</td>
                                    <td colspan="2" class="text-center">
                                        <a class="btn btn-secondary btn-sm" href="{% url 'tienda:editcategoria' categoria.id %}" type="button"><i class="bi bi-pencil-square"></i></a>
                                        <a class="btn btn-danger btn-sm" href="{% url 'tienda:deleteCategoria' categoria.id %}" type="button"><i class="bi bi-trash-fill"></i></a>
                                    </td>
                                </tr>
                                {% endfor %} {% else %}
                                <div class="text-center text-warning">
                                    <h3> No existen productos</h3>
                                </div>
                                {% endif %}
                            </tbody>
                        </table>
                        <div>
                            {% include 'paginator.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/contacto.html
{% extends 'layouts/tienda.html' %} {% block content %}

<div class="min-vh-100 d-flex flex-colum py-4">
    <div class="container">
        <h3 class="animate__animated animate__bounceInDown animate__delay-0.2s text-center">CONTACTO</h3>
        <div class="row">
            <div class="col-lg-6 col-sm-04 mx-auto animate__animated animate__bounceInUp animate__delay-0.3s">
                {% load crispy_forms_tags %}
                <form method="post" action="">
                    {% csrf_token %} {{ form | crispy }}
                    <div class="justify-content-center">
                        <button type="reset" class="btn btn-secondary mt-1 mx-2" button ">Cancelar</button>
                        <button type="submit " class="btn btn-danger mt-1 " button ">Enviar</button>
                    </div>
                </form>
            </div>
            <div class="col-lg-6 col-sm-04 mt-4 rounded animate__animated animate__backInRight animate__delay-0.4s embed-responsive embed-responsive-4by3">
                <iframe class="embed-responsive-item" src="https://www.google.com/maps/place/Almacenes+LOYOLA/@-0.2440382,-78.5350935,16.52z/data=!4m5!3m4!1s0x91d599b98295dee3:0xe35a853cf22ef267!8m2!3d-0.244265!4d-78.5332684"
                    style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/devoluciones.html
{% extends 'layouts/tienda.html' %}{% load static %} {% block content %}

<div class="min-vh-100 d-flex flex-colum py-2">
    <div class="container">
        <h3 class="animate__animated animate__bounceInDown animate__delay-0.3s text-center py-4">SERVICIO TÉCNICO</h3>
        <div class="row py-auto">
            <div class="col-10 mx-auto animate__animated animate__backInRight animate__delay-0.3s">
                <p class="text-justify font-weight-bold">TE OFRECEMOS</p>
                <p class="text-justify">
                    Mantenimiento y reparación de equipos de panadería como amasadoras, laminadoras, batidoras industriales, comerciales,profesionales, etc.
                </p>
                <p class="text-justify">Mantenimiento y reparación de equipos de gastronomía como exprimidores de naranja, procesadores industriales, jugueras,licuadoras industriales, comerciales y domésticas wafleras y creperas comerciales, microondas comerciales y domésticos, peladoras de papas cutter, freidoras de papas, molinos de carne, molinos de granos industriales y comerciales. </p>
                <p class="text-justify">
                    Mantenimiento y reparación de equipos de cafetería como cafetera capuchinera industriales, cafeteras comerciales de 100, 55 y 36 tazas.
                </p>

                <p class="text-justify">Mantenimiento y reparación de máquinas de helados.
                </p>

                <p class="text-justify">
                    Mantenimiento y reparación de equipos de peluquería como secadoras de cabello, máquinas de cabello, patilleras, planchas alisadoras, secadoras de pedestal, aceleradores de calor, esterilizadores, bases hidráulicas, etc.
                </p>
                <p class="text-justify">Mantenimiento y reparación de equipos de sastrería como planchas industriales y comerciales.
                </p>
                <p class="text-justify">Mantenimiento y reparación de equipos de cosmetología como Vacum Terapia, equipos de dermoabrasión, vaporizadores, gimnasia pasiva, peeling ultrasónico, ultrasonido, alta frecuencia, etc.
                </p>
            </div>
            <div class="col-10 text-right">
                <a href="/" class="btn btn-dark my-4 mx-auto">Atras</a>
            </div>
        </div>

    </div>
</div>

{% endblock %}

templates/garantia.html
{% extends 'layouts/tienda.html' %}{% load static %} {% block content %}

<div class="min-vh-100 d-flex flex-colum py-2">
    <div class="container">
        <h3 class="animate__animated animate__bounceInDown animate__delay-0.3s text-center py-4">PANDEMIA</h3>
        <div class="row py-auto">
            <div class="col-10 mx-auto animate__animated animate__backInRight animate__delay-0.3s">
                <p class="text-justify font-weight-bold">¡Quédate en casa! </p>
                <p class="text-justify">
                    Con la finalidad de precautelar vuestra salud y bienestar, desde el lunes 25 de abril del 2021 en un horario de 7:00 a 12:30 pm ofrecemos nuestros Servicios de Mantenimientos preventivos y correctivos a domicilio tomando en cuenta todas las medidas de seguridad determinadas por el COE.
                </p>
            </div>
            <div class="col-10 text-right">
                <a href="/" class="btn btn-dark my-4 mx-auto">Atras</a>
            </div>
        </div>

    </div>
</div>

{% endblock %}

templates/index.html
{% extends "layouts/tienda.html" %} {% load static %} {% block content %}
<div class="min-vh-100 d-flex flex-colum pb-3">
    <div class="container">

        <!-- Encabezado-->
        <header class="bg-dark py-3 rounded-bottom animate__animated animate__zoomIn animate__delay-0.3s">
            <div class="text-center text-white ">
                <h1 class="display-4 fw-bolder animate__animated animate__bounceInDown animate__delay-0.4s">Almacenes Loyola Servicio Técnico Especializado</h1>
                
            </div>
        </header>

        <!-- Seccion-->
        <div class="pt-3">
            <form class="d-flex d-md-inlne-block form-inline justify-content-end" method="POST" action="">
                {% csrf_token %}
                <div class="input-group">
                    <input type="text" class="form-control bg-light border-1 small text-center" name="buscador" placeholder="Buscar.." value="{{ request.POST.buscador }}">
                    <div class="input-group-append">
                        <button class="btn btn-danger mx-1" type="submit"> 
                    <i class="bi bi-search bi-sm"></i>
                </button>
                    </div>
                </div>
            </form>
        </div>

        <section class="py-2">
            <div class="container px-4 px-lg-5 mt-2 animate__animated animate__fadeIn animate__delay-0.3s">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% if entity %} {% for producto in entity %}
                    <div class="col my-3">
                        <div class="card h-100 text-center py-3">
                            <!-- Imagen Producto-->
                            {% if producto.imagen %}
                            <img class="mx-auto d-block img-fluid" src="{{ producto.imagen.url }}" alt="producto" width="60px%" /> {% else %}
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="sinImagen" /> {% endif %}
                            <!-- Detalles del producto-->
                            {% load humanize %}
                            <div class="card-body p-3">
                                <div class="text-center">
                                    <!-- Nombre Producto-->
                                    <h5 class="fw-bolder">{{ producto.nombre }}</h5>
                                    <!-- Costo Producto-->
                                    $ {{ producto.precio | intcomma }}
                                </div>
                            </div>
                            <!-- Producto -->
                            <div class="card-footer p-2 pt-2 border-top-0 bg-transparent">
                                <div class="text-center">
                                    <a class="btn btn-dark mt-auto" href="{% url 'tienda:detalleproducto' producto.id %}">Ver detalle</a> {% if user.is_authenticated%}
                                    <a href="{% url 'tienda:addcart' producto.id %}" class="btn btn-danger mt-2" type="button">
                                        <i class="bi-cart-fill me-1"></i> Agregar al Carrito
                                    </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %} {% else %}
                    <div class="text-center text-warning">
                        <h3> No existen Productos</h3>
                    </div>
                    {% endif %}
                </div>

                <div>
                    {% include 'paginator.html' %}
                </div>
            </div>

        </section>
    </div>
</div>
{% endblock %}

templates/nosotros.html
{% extends 'layouts/tienda.html' %}{% load static %} {% block content %}

<div class="min-vh-100 d-flex flex-colum py-2">
    <div class="container">
        <h3 class="animate__animated animate__bounceInDown animate__delay-0.3s text-center py-4">ALMACENES LOYOLA</h3>
        <div class="row py-auto">
            <div class="col-lg-8">
                <p class="animate__animated animate__backInRight animate__delay-0.3s text-justify">
                    Almacenes Loyola ha estado cumpliendo con lo prometido desde nuestra apertura. Nuestro objetivo es ofrecer una experiencia al cliente superior y un enorme valor para nuestros clientes otorgando servicios especializados de mantenimiento y reparación de equipos industriales de gastronomía y peluquería con repuestos de calidad y mano de obra especializada.
                </p>
                <p class="animate__animated animate__backInRight animate__delay-0.3s text-justify">
                    Contamos con personal técnico de amplia experiencia en el sector lo que nos garantiza trabajos de calidad ayudando a que nuestros clientes puedan mantener operativos al ciento por ciento sus herramientas de trabajo.
                </p>
                <p class="animate__animated animate__backInRight animate__delay-0.3s text-justify">
                    Apreciamos a nuestros clientes y agradecemos tus comentarios, sugerencias o pedidos de reparación. Usa nuestra página Contáctanos para decirnos qué es lo que estamos haciendo bien y qué es lo que podemos mejorar.
                </p>
            </div>

            <div class="col-lg-4 animate__animated animate__bounceInUp animate__delay-0.4s ">
                <img class="img-fluid ml-auto" src="{% static 'assets/team.png' %}" alt="team">
            </div>

        </div>
        <div class="row animate__animated animate__bounceInUp animate__delay-1s">
            <p class="mb-1">Teléfono: +593 983 568 610 | 02 6019024</p>
            <p class="mb-1">Correo Electronico: almacenesloyola@gmail.com</p>
            <p> Quito, Ecuador</p>
        </div>
    </div>
</div>

{% endblock %}

templates/paginator.html
{% if paginator.num_pages > 1 %}
    
    <div class="d-flex justify-content-center">
        <ul class="pagination">
            {% if entity.has_previous %}
                <li class="page-item d-none d-sm-block">
                    <a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a>
                </li>
            {% endif %} 

            {% for page in paginator.page_range %} 
                {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                    {% if entity.next_page_number != paginator.num_pages%}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                        </li>
                    {% endif %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ paginator.num_pages }}#pagtable">
                            {{paginator.num_pages}}
                        </a>
                    </li>
                {% endif %} 

                {% if page == entity.number and page > 7 %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
                    </li>
                {% endif %} 

                {% if page < 7 or page == entity.number %} 
                    <li class="page-item {% if page == entity.number %} active{% endif %}">
                        <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
                    </li>
                {% endif %} 
            {% endfor %} 

            {% if entity.has_next %}
                <li class="page-item d-none d-sm-block">
                    <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
                </li>
            {% endif %}
        </ul>
    </div>

    <div class="d-flex justify-content-center d-sm-none">
        {% if entity.has_previous %}
            <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span> 
        {% endif %} 

        {% if entity.has_next %}
            <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span> 
        {% endif %}
            <br>
            <br>
    </div>
    
{% endif %}